package co.tecnoamti.java.asistenciavideotel.dominio;
// Generated 24/08/2014 18:19:14 by Hibernate Tools 3.2.1.GA



/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private byte cid;
     private Byte sid;
     private String descripcion;

    public Comentario() {
    }

	
    public Comentario(byte cid) {
        this.cid = cid;
    }
    public Comentario(byte cid, Byte sid, String descripcion) {
       this.cid = cid;
       this.sid = sid;
       this.descripcion = descripcion;
    }
   
    public byte getCid() {
        return this.cid;
    }
    
    public void setCid(byte cid) {
        this.cid = cid;
    }
    public Byte getSid() {
        return this.sid;
    }
    
    public void setSid(Byte sid) {
        this.sid = sid;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


