package co.tecnoamti.java.asistenciavideotel.dominio;
// Generated 24/08/2014 18:19:14 by Hibernate Tools 3.2.1.GA



/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private byte hid;
     private Turno turno;
     private Empleado empleado;

    public Horario() {
    }

	
    public Horario(byte hid) {
        this.hid = hid;
    }
    public Horario(byte hid, Turno turno, Empleado empleado) {
       this.hid = hid;
       this.turno = turno;
       this.empleado = empleado;
    }
   
    public byte getHid() {
        return this.hid;
    }
    
    public void setHid(byte hid) {
        this.hid = hid;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }




}


