package co.tecnoamti.java.asistenciavideotel.dominio;
// Generated 24/08/2014 18:19:14 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Marcacion generated by hbm2java
 */
public class Marcacion  implements java.io.Serializable {


     private int maid;
     private Asistencia asistencia;
     private Date entrada;
     private Date salida;
     private Byte etolerancia;
     private Byte stolerancia;
     private Boolean modificado;
     private Date fmodificado;
     private Boolean estado;

    public Marcacion() {
    }

	
    public Marcacion(int maid) {
        this.maid = maid;
    }
    public Marcacion(int maid, Asistencia asistencia, Date entrada, Date salida, Byte etolerancia, Byte stolerancia, Boolean modificado, Date fmodificado, Boolean estado) {
       this.maid = maid;
       this.asistencia = asistencia;
       this.entrada = entrada;
       this.salida = salida;
       this.etolerancia = etolerancia;
       this.stolerancia = stolerancia;
       this.modificado = modificado;
       this.fmodificado = fmodificado;
       this.estado = estado;
    }
   
    public int getMaid() {
        return this.maid;
    }
    
    public void setMaid(int maid) {
        this.maid = maid;
    }
    public Asistencia getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(Asistencia asistencia) {
        this.asistencia = asistencia;
    }
    public Date getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Date entrada) {
        this.entrada = entrada;
    }
    public Date getSalida() {
        return this.salida;
    }
    
    public void setSalida(Date salida) {
        this.salida = salida;
    }
    public Byte getEtolerancia() {
        return this.etolerancia;
    }
    
    public void setEtolerancia(Byte etolerancia) {
        this.etolerancia = etolerancia;
    }
    public Byte getStolerancia() {
        return this.stolerancia;
    }
    
    public void setStolerancia(Byte stolerancia) {
        this.stolerancia = stolerancia;
    }
    public Boolean getModificado() {
        return this.modificado;
    }
    
    public void setModificado(Boolean modificado) {
        this.modificado = modificado;
    }
    public Date getFmodificado() {
        return this.fmodificado;
    }
    
    public void setFmodificado(Date fmodificado) {
        this.fmodificado = fmodificado;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


