package co.tecnoamti.java.asistenciavideotel.dominio;
// Generated 24/08/2014 18:19:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tcategoria generated by hbm2java
 */
public class Tcategoria  implements java.io.Serializable {


     private byte tcid;
     private Byte descripcion;
     private Set<Turno> turnos = new HashSet<Turno>(0);

    public Tcategoria() {
    }

	
    public Tcategoria(byte tcid) {
        this.tcid = tcid;
    }
    public Tcategoria(byte tcid, Byte descripcion, Set<Turno> turnos) {
       this.tcid = tcid;
       this.descripcion = descripcion;
       this.turnos = turnos;
    }
   
    public byte getTcid() {
        return this.tcid;
    }
    
    public void setTcid(byte tcid) {
        this.tcid = tcid;
    }
    public Byte getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(Byte descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Turno> getTurnos() {
        return this.turnos;
    }
    
    public void setTurnos(Set<Turno> turnos) {
        this.turnos = turnos;
    }




}


