package co.tecnomati.java.asistenciavideotel.dominio;
// Generated 23/09/2014 15:09:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer eid;
     private Sector sector;
     private Integer dni;
     private String telefono;
     private String apellido;
     private String nombre;
     private byte[] foto;
     private Boolean estado;
     private Boolean administrador;
     private String clave;
     private Set<Asistencia> asistencias = new HashSet<Asistencia>(0);
     private Set<Diatrabajo> diatrabajos = new HashSet<Diatrabajo>(0);

    public Empleado() {
    }

    public Empleado(Sector sector, Integer dni, String telefono, String apellido, String nombre, byte[] foto, Boolean estado, Boolean administrador, String clave, Set<Asistencia> asistencias, Set<Diatrabajo> diatrabajos) {
       this.sector = sector;
       this.dni = dni;
       this.telefono = telefono;
       this.apellido = apellido;
       this.nombre = nombre;
       this.foto = foto;
       this.estado = estado;
       this.administrador = administrador;
       this.clave = clave;
       this.asistencias = asistencias;
       this.diatrabajos = diatrabajos;
    }
   
    public Integer getEid() {
        return this.eid;
    }
    
    public void setEid(Integer eid) {
        this.eid = eid;
    }
    public Sector getSector() {
        return this.sector;
    }
    
    public void setSector(Sector sector) {
        this.sector = sector;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Boolean getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Boolean administrador) {
        this.administrador = administrador;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set<Asistencia> getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set<Asistencia> asistencias) {
        this.asistencias = asistencias;
    }
    public Set<Diatrabajo> getDiatrabajos() {
        return this.diatrabajos;
    }
    
    public void setDiatrabajos(Set<Diatrabajo> diatrabajos) {
        this.diatrabajos = diatrabajos;
    }




}


