package co.tecnomati.java.asistenciavideotel.dominio;
// Generated 24/08/2014 18:19:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sector generated by hbm2java
 */
public class Sector  implements java.io.Serializable {


     private byte sid;
     private Empresa empresa;
     private String descripcion;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Sector() {
    }

	
    public Sector(byte sid) {
        this.sid = sid;
    }
    public Sector(byte sid, Empresa empresa, String descripcion, Set<Empleado> empleados) {
       this.sid = sid;
       this.empresa = empresa;
       this.descripcion = descripcion;
       this.empleados = empleados;
    }
   
    public byte getSid() {
        return this.sid;
    }
    
    public void setSid(byte sid) {
        this.sid = sid;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


