package co.tecnomati.java.asistenciavideotel.dominio;
// Generated 26/09/2014 17:58:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sector generated by hbm2java
 */
public class Sector  implements java.io.Serializable {


     private Integer sid;
     private Empresa empresa;
     private String descripcion;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Sector() {
    }

    public Sector(Empresa empresa, String descripcion, Set<Empleado> empleados) {
       this.empresa = empresa;
       this.descripcion = descripcion;
       this.empleados = empleados;
    }
   
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


