package co.tecnomati.java.asistenciavideotel.dominio;
// Generated 24/08/2014 18:19:14 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Turno generated by hbm2java
 */
public class Turno  implements java.io.Serializable {


     private byte tid;
     private Tcategoria tcategoria;
     private Date entrada;
     private Date salida;
     private String dias;
     private Date etolerancia;
     private Date stolerancia;
     private Byte nturno;
     private Set<Horario> horarios = new HashSet<Horario>(0);

    public Turno() {
    }

	
    public Turno(byte tid) {
        this.tid = tid;
    }
    public Turno(byte tid, Tcategoria tcategoria, Date entrada, Date salida, String dias, Date etolerancia, Date stolerancia, Byte nturno, Set<Horario> horarios) {
       this.tid = tid;
       this.tcategoria = tcategoria;
       this.entrada = entrada;
       this.salida = salida;
       this.dias = dias;
       this.etolerancia = etolerancia;
       this.stolerancia = stolerancia;
       this.nturno = nturno;
       this.horarios = horarios;
    }
   
    public byte getTid() {
        return this.tid;
    }
    
    public void setTid(byte tid) {
        this.tid = tid;
    }
    public Tcategoria getTcategoria() {
        return this.tcategoria;
    }
    
    public void setTcategoria(Tcategoria tcategoria) {
        this.tcategoria = tcategoria;
    }
    public Date getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Date entrada) {
        this.entrada = entrada;
    }
    public Date getSalida() {
        return this.salida;
    }
    
    public void setSalida(Date salida) {
        this.salida = salida;
    }
    public String getDias() {
        return this.dias;
    }
    
    public void setDias(String dias) {
        this.dias = dias;
    }
    public Date getEtolerancia() {
        return this.etolerancia;
    }
    
    public void setEtolerancia(Date etolerancia) {
        this.etolerancia = etolerancia;
    }
    public Date getStolerancia() {
        return this.stolerancia;
    }
    
    public void setStolerancia(Date stolerancia) {
        this.stolerancia = stolerancia;
    }
    public Byte getNturno() {
        return this.nturno;
    }
    
    public void setNturno(Byte nturno) {
        this.nturno = nturno;
    }
    public Set<Horario> getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }




}


